### PR TITLE
[WIP] Experimental detox based tests

### PR DESCRIPTION
**Pull request by cloudify**
Experimental tests based on [Detox](https://github.com/wix/detox) (currently iOS only)

detox-tests

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please include a Pivotal story at the beginning of the PR title (see below).
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  Remember to fix the PR title by removing WIP wording when ready
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  Could not get info from npm on <a href='https://www.npmjs.com/package/@types/node'><code>&#64;types/node</code></a></a>
  </td>
    </tr>
  </tbody>
</table>



  Example of PR titles that include pivotal stories:

  * single story: `[#123456] my PR title`
  * multiple stories: `[#123456,#123457,#123458] my PR title`

    

New dependencies added: <a href='https://www.npmjs.com/package/@types/node'><code>&#64;types/node</code></a> and <a href='https://www.npmjs.com/package/detox'><code>detox</code></a>.


<h2><a href="https://github.com/wix/detox#readme">detox</a></h2>
<p>Author: Tal Kol</p>
<p>Description: E2E tests and automation for mobile</p>
<p>Homepage: <a href="https://github.com/wix/detox#readme">https://github.com/wix/detox#readme</a></p>

<table>
  <thead><tr><th></th><th width="100%"></th></tr></thead>
  <tr><td>Created</td><td>about 3 years ago</td></tr><tr><td>Last Updated</td><td>6 days ago</td></tr><tr><td>License</td><td>MIT</td></tr><tr><td>Maintainers</td><td>6</td></tr><tr><td>Releases</td><td>99</td></tr><tr><td>Direct Dependencies</td><td><a href='https://www.npmjs.com/package/child-process-promise'><code>child-process-promise</code></a>, <a href='https://www.npmjs.com/package/commander'><code>commander</code></a>, <a href='https://www.npmjs.com/package/detox-server'><code>detox-server</code></a>, <a href='https://www.npmjs.com/package/fs-extra'><code>fs-extra</code></a>, <a href='https://www.npmjs.com/package/get-port'><code>get-port</code></a>, <a href='https://www.npmjs.com/package/ini'><code>ini</code></a>, <a href='https://www.npmjs.com/package/lodash'><code>lodash</code></a>, <a href='https://www.npmjs.com/package/npmlog'><code>npmlog</code></a>, <a href='https://www.npmjs.com/package/shell-utils'><code>shell-utils</code></a>, <a href='https://www.npmjs.com/package/tail'><code>tail</code></a>, <a href='https://www.npmjs.com/package/telnet-client'><code>telnet-client</code></a> and <a href='https://www.npmjs.com/package/ws'><code>ws</code></a></td></tr>
</table>

<details>
<summary><code>README</code></summary></br>

# detox

Graybox End-to-End Tests and Automation Library for Mobile

[NPM Version](https://www.npmjs.com/package/detox)
[Build Status](https://travis-ci.org/wix/detox)
[NPM Downloads](https://www.npmjs.com/package/detox)


For more information go to our [README](https://github.com/wix/detox/blob/master/README.md) or [Read The Docs](https://github.com/wix/detox/tree/master/docs)

</details>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by fpersico** [comment]
Looks good. Let me know if you need my help in some way.

**Comment by cloudify** [comment]
Thanks, I'm going to trying a couple things more (navigation and taking screenshots) - I think we will also have to create a Docker image that sets up the local IdP for logging in with SPID (unless we can use the AgID IdP) - cc @lussoluca

**Comment by fpersico** [comment]
@cloudify Screenshots and other usefull stuff are goin to be merged soon in detox with this PR https://gist.github.com/cjcaj/8c25bb5538f54a4810dc36025aa7a3d8#file-helpers-js

In the meantime you can use this snipplet to take screenshot on ios https://gist.github.com/cjcaj/8c25bb5538f54a4810dc36025aa7a3d8#file-helpers-js

**Comment by cloudify** [comment]
This is currently failing with a timeout from the simulator (works fine locally) - I suspect it's related to https://github.com/wix/detox/issues/155

**Comment by cloudify** [comment]
Possible fix: https://github.com/wix/detox/issues/689

**Comment by cloudify** [comment]
Tests are a little flacky on circleci due to the restricted resources of the VM, merging for now.

**Pull request merged**
