### PR TITLE
[#160983940] Fix and improve connection bar style.

### PR DESCRIPTION
**Pull request by DenisFrezzato**
@matteodesanti I don't have the exact background colour and opacity that the bar should have. And the icon is missing.

offline-message-list
offline-wallet
simulator screen shot - iphone 6 - 2018-10-18 at 17 55 16
simulator screen shot - iphone x - 2018-10-18 at 17 55 13

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Remember to fix the PR title by removing WIP wording when ready
  </td>
    </tr>
  </tbody>
</table>



## Affected stories

  * 🐞 [#160983940](https://www.pivotaltracker.com/story/show/160983940): Header iPhone X

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by DenisFrezzato** [comment]
The message is too long, it's not going to fit with smaller devices.

screenshot_1540042004
screenshot_1540042017

**Comment by cloudify** [comment]
@DenisFrezzato looks great thanks, we can shorten the message to "You are offline! some features will not work" and "Sei offline! Qualcosa non funzionerà"

**Comment by cloudify** [comment]
@DenisFrezzato at least I would just leave the "offline" word, the icon alone may not be clear enough

**Comment by DenisFrezzato** [comment]
@cloudify Done. It looks fine with a 4" device.

**Comment by cloudify** [comment]
On the messages screen there is an extra vertical space that is not present on the other screens

image

**Comment by cloudify** [comment]
No extra space

image

**Pull request merged**
