### PR TITLE
Adds Pot container for tracking the state of remote data

### PR DESCRIPTION
**Pull request by cloudify**
This is the porting of a type I used often in my Scala code, when I had to track the state of remote data (esp. useful in UI), see https://diode.suzaku.io/advanced/Pot.html

With this PR I propose to wrap data coming from the proxy within a `Pot<>` class to be able to track its state and render the UI accordingly.

This would be used, for instance, in `ProfileState`:

```js

import * as pot from "../../utils/pot"

export type ProfileState = pot.Pot<ApiProfile>

export const INITIAL_STATE = pot.empty<ApiProfile>()

```

TODO: a `fold` method similar to `Either`'s

To get an idea on how it would work in the UI, see the examples [here](https://diode.suzaku.io/UsageWithReact.html)

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Please include a Pivotal story at the beginning of the PR title (see below).
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  Remember to fix the PR title by removing WIP wording when ready
  </td>
    </tr>
  </tbody>
</table>



  Example of PR titles that include pivotal stories:

  * single story: `[#123456] my PR title`
  * multiple stories: `[#123456,#123457,#123458] my PR title`

    
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by gunzip** [comment]
if only this was written in TS we could have used fp-ts (to get monadic map / flatMap / fold) for free, see

https://github.com/gcanti/fp-ts/blob/master/examples/Moore.ts <-- custom monad
https://github.com/gcanti/fp-ts/blob/master/examples/ixIO.ts <-- a state machine

**Comment by cloudify** [comment]
Yes there is actually a TS implementation of a similar concept (albeit a simpler version) [here](https://github.com/devex-web-frontend/remote-data-ts), based on a [post by @gcanti](https://medium.com/@gcanti/slaying-a-ui-antipattern-with-flow-5eed0cfb627b)

**Comment by cloudify** [comment]
@fpersico I've noticed that `ApiProfile` is duplicated in the `GlobalState`, it's stored both in `LoggedInUserState` and in `ProfileState`, we should probably get rid of one of the two

**Comment by fpersico** [comment]
The old profile state is here just because some screen use it, it is managed by redux-thunk actions and it mix profile fileds (like inbox enabled, fiscal_code) with session fields (like token). The new ProfileState is managed with redux-saga and only manage the profile filelds. I am going to create another saga just to manage the session (login/check token/refresh) and put it in a store section called "session". As soon as it is ready we will remove redux-thunk from the project and also the old profile state.

**Comment by cloudify** [comment]
Closing this PR as I'm moving the code to [italia-ts-commons](https://github.com/teamdigitale/italia-ts-commons)

**Comment by cloudify** [comment]
In fact, I think we can now use [this library](https://github.com/devex-web-frontend/remote-data-ts)

**Pull request closed without merging**
