### PR TITLE
[#161368623] Store and show messages read state

### PR DESCRIPTION
**Pull request by fpersico**
newmessages

### CODE REVIEW

**Comment by digitalcitizenship** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Remember to fix the PR title by removing WIP wording when ready
  </td>
    </tr>
  </tbody>
</table>



## Affected stories

  * 🌟 [#161368623](https://www.pivotaltracker.com/story/show/161368623): Come CIT, nella lista messaggi, voglio vedere in maniera diversa i messaggi di cui non ho ancora visualizzato il dettaglio

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by cloudify** [comment]
@fpersico if possible, the blue button should be on the left gutter and the text should be aligned consistently, like here:

**Comment by cloudify** [comment]
@fpersico if possible, the blue button should be on the left gutter, like:

image

**Comment by fpersico** [comment]
@cloudify Yes i think it is possible. Do we need to wait @matteodesanti to confirm this change?

**Comment by fpersico** [comment]
@cloudify new ui

newmessage

**Comment by cloudify** [comment]
Excellent, thanks @fpersico

**Pull request merged**
