### PR TITLE
[#161376443] Trucate header title when necessary

### PR DESCRIPTION
**Pull request by fpersico**
header_title

### CODE REVIEW

**Comment by fpersico** [comment]
@cloudify Are you refactoring also the screens related to the Wallet to use the default screen wrappers?

**Comment by digitalcitizenship** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Remember to fix the PR title by removing WIP wording when ready
  </td>
    </tr>
  </tbody>
</table>



## Affected stories

  * 🐞 [#161376443](https://www.pivotaltracker.com/story/show/161376443): Se il valore del titolo dello screen nella header è troppo lungo NON deve andare su due righe, ma deve essere troncato e mostrare i puntini...

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by cloudify** [comment]
@fpersico let me know when you have tested this solution on iOS too

**Comment by fpersico** [comment]
@cloudify It also works on iOS

truncate

**Pull request merged**
