### PR TITLE
[#159195555] update term of use + implement contextual help to host bolded text & links

### PR DESCRIPTION
**Pull request by valentinacala**
This pr implements the Contextual Help to host, as content, not only plain text but also partially bolded text or links.
It is required to insert, as contextual help, the term of use. This contextual help is added to the actual 
SpidInformationRequestScreen. 

Are there other access points to term of use? are they contextual help too?

(WIP because lint errors can't be fixed yet - i'm now working on solve it)

### CODE REVIEW

**Comment by cloudify** [comment]
@fpersico how would you suggest to keep the content of the terms outside the i18n translations (they're too long to store them in the json)

**Comment by digitalcitizenship** [comment]
## Affected stories

  * ⚙️ [#159195555](https://www.pivotaltracker.com/story/show/159195555): Come CIT voglio vedere i termini e condizioni d'uso corretti

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by valentinacala** [comment]
Actually terms are only in Italian to avoid formal mistakes on the content

**Comment by cloudify** [comment]
We can go ahead with this, I've opened a story to convert the text to markdown https://www.pivotaltracker.com/story/show/159554061

**Pull request merged**
